### ISSUE TITLE
Support multiple payloads in packet

### ISSUE THREAD

**Issue by zhuowei** [Shragei/SplatNet#3]
At least two packet types can contain multiple payloads (NinFrame, according to http://mk8.tockdom.com/wiki/MK8_Network_Protocol, can have multiple subheaders, and the compressed Player packets may contain multiple payloads in the compressed payload); the dissector's Format function should support those packets, perhaps by returning an array of decoded payloads.

**Comment by Shragei** [comment]
NinFrame looks like it can, but can only have a single payload from what I have seen. Now there is a bug in how the NinFrame is created on the WiiU, where buffers are recycled without checking the buffer size. The bug can be seen as frames with extra padding, 100+ bytes in some cases. 
The decoder will now keep trying additional dissectors if current dissector doesn't consume the whole payload. This can be found in the testing branch. A bug in the tools has to be fixed before I can test it.

**Comment by Shragei** [comment]
Removed the runtime errors from the decoder. Able to handle multiple dissectors now.
